/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-05-11 22:06:10
*/

module k_lut_block
(
  In_0,
  In_1,
  In_2,
  In_3,
  f_sel,
  is_synced,
  clk,
  out,
  out_ff
);

  wire _0_;
  wire _1_;
  input In_0;
  wire In_0;
  input In_1;
  wire In_1;
  input In_2;
  wire In_2;
  input In_3;
  wire In_3;
  input clk;
  wire clk;
  wire \config_data[0] ;
  wire \config_data[1] ;
  wire \config_data[2] ;
  wire \config_data[3] ;
  input [1:0] f_sel;
  wire [1:0] f_sel;
  input is_synced;
  wire is_synced;
  output out;
  wire out;
  output out_ff;
  wire out_ff;

  sky130_fd_sc_hd__mux4_2
  _2_
  (
    .A0(\config_data[0] ),
    .A1(\config_data[1] ),
    .A2(\config_data[2] ),
    .A3(\config_data[3] ),
    .S0(f_sel[0]),
    .S1(f_sel[1]),
    .X(_1_)
  );


  sky130_fd_sc_hd__and2_0
  _3_
  (
    .A(is_synced),
    .B(_1_),
    .X(_0_)
  );


  sky130_fd_sc_hd__nor2b_1
  _4_
  (
    .A(is_synced),
    .B_N(_1_),
    .Y(out)
  );


  sky130_fd_sc_hd__dfxtp_1
  _5_
  (
    .CLK(clk),
    .D(In_0),
    .Q(\config_data[0] )
  );


  sky130_fd_sc_hd__dfxtp_1
  _6_
  (
    .CLK(clk),
    .D(In_1),
    .Q(\config_data[1] )
  );


  sky130_fd_sc_hd__dfxtp_1
  _7_
  (
    .CLK(clk),
    .D(In_2),
    .Q(\config_data[2] )
  );


  sky130_fd_sc_hd__dfxtp_1
  _8_
  (
    .CLK(clk),
    .D(In_3),
    .Q(\config_data[3] )
  );


  sky130_fd_sc_hd__dfxtp_1
  _9_
  (
    .CLK(clk),
    .D(_0_),
    .Q(out_ff)
  );


endmodule

