# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/University Stuff/Vivado/10th Lab/lab_1/lab_1.srcs/sources_1/bd/task_1_part_2/ip/task_1_part_2_xbar_0/task_1_part_2_xbar_0.xci
# IP: The module: 'task_1_part_2_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/University Stuff/Vivado/10th Lab/lab_1/lab_1.srcs/sources_1/bd/task_1_part_2/ip/task_1_part_2_xbar_0/task_1_part_2_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'task_1_part_2_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/University Stuff/Vivado/10th Lab/lab_1/lab_1.srcs/sources_1/bd/task_1_part_2/ip/task_1_part_2_xbar_0/task_1_part_2_xbar_0.xci
# IP: The module: 'task_1_part_2_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/University Stuff/Vivado/10th Lab/lab_1/lab_1.srcs/sources_1/bd/task_1_part_2/ip/task_1_part_2_xbar_0/task_1_part_2_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'task_1_part_2_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
