/* Generated by Yosys 0.57+218 (git sha1 7ebd97216, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module k_lut_block(In_0, In_1, In_2, In_3, f_sel, is_synced, clk, out, out_ff);
  input In_0;
  wire In_0;
  input In_1;
  wire In_1;
  input In_2;
  wire In_2;
  input In_3;
  wire In_3;
  input [1:0] f_sel;
  wire [1:0] f_sel;
  input is_synced;
  wire is_synced;
  input clk;
  wire clk;
  output out;
  wire out;
  output out_ff;
  wire out_ff;
  wire _0_;
  wire _1_;
  wire [3:0] config_data;
  wire \demux_inst.out0 ;
  wire \demux_inst.sel ;
  wire \dff_inst.clk ;
  wire \dff_inst.q ;
  wire [3:0] \mux_inst.data ;
  wire [1:0] \mux_inst.sel ;
  wire \sr_inst.clk ;
  wire \sr_inst.in_0 ;
  wire \sr_inst.in_1 ;
  wire \sr_inst.in_2 ;
  wire \sr_inst.in_3 ;
  wire [3:0] \sr_inst.q ;
  sky130_fd_sc_hd__mux4_2 _2_ (
    .A0(\sr_inst.q [0]),
    .A1(\sr_inst.q [1]),
    .A2(\sr_inst.q [2]),
    .A3(\sr_inst.q [3]),
    .S0(f_sel[0]),
    .S1(f_sel[1]),
    .X(_1_)
  );
  sky130_fd_sc_hd__and2_0 _3_ (
    .A(is_synced),
    .B(_1_),
    .X(_0_)
  );
  sky130_fd_sc_hd__nor2b_1 _4_ (
    .A(is_synced),
    .B_N(_1_),
    .Y(out)
  );
  sky130_fd_sc_hd__dfxtp_1 _5_ (
    .CLK(clk),
    .D(In_1),
    .Q(\sr_inst.q [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _6_ (
    .CLK(clk),
    .D(In_2),
    .Q(\sr_inst.q [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _7_ (
    .CLK(clk),
    .D(In_3),
    .Q(\sr_inst.q [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _8_ (
    .CLK(clk),
    .D(_0_),
    .Q(\dff_inst.q )
  );
  sky130_fd_sc_hd__dfxtp_1 _9_ (
    .CLK(clk),
    .D(In_0),
    .Q(\sr_inst.q [0])
  );
  assign config_data = \sr_inst.q ;
  assign \demux_inst.out0  = out;
  assign \demux_inst.sel  = is_synced;
  assign \dff_inst.clk  = clk;
  assign \mux_inst.data  = \sr_inst.q ;
  assign \mux_inst.sel  = f_sel;
  assign out_ff = \dff_inst.q ;
  assign \sr_inst.clk  = clk;
  assign \sr_inst.in_0  = In_0;
  assign \sr_inst.in_1  = In_1;
  assign \sr_inst.in_2  = In_2;
  assign \sr_inst.in_3  = In_3;
endmodule
