# Define the library path
set lib_path "/mnt/FA685EF1685EAC5F/University/Advanced-Microelectronics-Lab/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib"

# Read the standard cell library
read_liberty $lib_path

# Read the synthesized Verilog netlist generated by Yosys in Task 2
read_verilog k_lut_synth.v

# Link the design to the top module
link_design k_lut_block

# Read SDC constraints (Crucial for defining the clock period for power calcs)
read_sdc k_lut_constraints.sdc

# =========================================================================
# REQUIREMENT: Set switching activities
# =========================================================================

# inputs = 0.2
set_power_activity -input_port In_0 -activity 0.2
set_power_activity -input_port In_1 -activity 0.2
set_power_activity -input_port In_2 -activity 0.2
set_power_activity -input_port In_3 -activity 0.2

# config = 0.01 (Wrapped in {} so Tcl doesn't try to evaluate [0] as a command)
set_power_activity -input_port {f_sel[0]} -activity 0.01
set_power_activity -input_port {f_sel[1]} -activity 0.01

# is_syncd = 0.05
set_power_activity -input_port is_synced -activity 0.05

# clk = 1.0 
# (OpenSTA usually derives this from create_clock, but we explicitly set it to fulfill your requirement)
set_power_activity -input_port clk -activity 1.0

# =========================================================================
# Generate Power Report
# =========================================================================
report_power -digits 4 > power.rpt

puts "\n=== Power Analysis Complete ==="
puts "--> Full power report written to: power.rpt"