# Define the library path
set lib_path "/mnt/FA685EF1685EAC5F/University/Advanced-Microelectronics-Lab/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib"

# Read the Liberty library
read_liberty $lib_path

# Read the synthesized Verilog netlist generated by Yosys
read_verilog k_lut_synth.v

# Link the design to the top module
link_design k_lut_block

# Read SDC constraints
read_sdc k_lut_constraints.sdc

# REQUIREMENT: Run Setup Timing Analysis and output to file
report_checks -path_delay max -format full_clock_expanded -digits 4 > setup.rpt
puts "--> Setup analysis written to setup.rpt"

# REQUIREMENT: Run Hold Timing Analysis and output to file
report_checks -path_delay min -format full_clock_expanded -digits 4 > hold.rpt
puts "--> Hold analysis written to hold.rpt"

# Output data to terminal to easily find the critical path and calculate Fmax
puts "\n=== Setup Timing Summary (For Fmax Calculation) ==="
report_worst_slack -max