# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/University Stuff/Vivado/10th Lab/lab_1/lab_1.srcs/sources_1/bd/task_0/ip/task_0_axi_gpio_4_0/task_0_axi_gpio_4_0.xci
# IP: The module: 'task_0_axi_gpio_4_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/University Stuff/Vivado/10th Lab/lab_1/lab_1.srcs/sources_1/bd/task_0/ip/task_0_axi_gpio_4_0/task_0_axi_gpio_4_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'task_0_axi_gpio_4_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/University Stuff/Vivado/10th Lab/lab_1/lab_1.srcs/sources_1/bd/task_0/ip/task_0_axi_gpio_4_0/task_0_axi_gpio_4_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'task_0_axi_gpio_4_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/University Stuff/Vivado/10th Lab/lab_1/lab_1.srcs/sources_1/bd/task_0/ip/task_0_axi_gpio_4_0/task_0_axi_gpio_4_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'task_0_axi_gpio_4_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/University Stuff/Vivado/10th Lab/lab_1/lab_1.srcs/sources_1/bd/task_0/ip/task_0_axi_gpio_4_0/task_0_axi_gpio_4_0.xci
# IP: The module: 'task_0_axi_gpio_4_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/University Stuff/Vivado/10th Lab/lab_1/lab_1.srcs/sources_1/bd/task_0/ip/task_0_axi_gpio_4_0/task_0_axi_gpio_4_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'task_0_axi_gpio_4_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/University Stuff/Vivado/10th Lab/lab_1/lab_1.srcs/sources_1/bd/task_0/ip/task_0_axi_gpio_4_0/task_0_axi_gpio_4_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'task_0_axi_gpio_4_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/University Stuff/Vivado/10th Lab/lab_1/lab_1.srcs/sources_1/bd/task_0/ip/task_0_axi_gpio_4_0/task_0_axi_gpio_4_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'task_0_axi_gpio_4_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
