# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/University Stuff/Vivado/10th Lab/lab_1/lab_1.srcs/sources_1/bd/soc_task_0/ip/soc_task_0_processing_system7_0_0/soc_task_0_processing_system7_0_0.xci
# IP: The module: 'soc_task_0_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/University Stuff/Vivado/10th Lab/lab_1/lab_1.srcs/sources_1/bd/soc_task_0/ip/soc_task_0_processing_system7_0_0/soc_task_0_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_task_0_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/University Stuff/Vivado/10th Lab/lab_1/lab_1.srcs/sources_1/bd/soc_task_0/ip/soc_task_0_processing_system7_0_0/soc_task_0_processing_system7_0_0.xci
# IP: The module: 'soc_task_0_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/University Stuff/Vivado/10th Lab/lab_1/lab_1.srcs/sources_1/bd/soc_task_0/ip/soc_task_0_processing_system7_0_0/soc_task_0_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_task_0_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
