-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity MAC_small_hls is
port (
    ap_clk : IN STD_LOGIC;
    rst_r : IN STD_LOGIC;
    valid : IN STD_LOGIC;
    idx : IN STD_LOGIC_VECTOR (11 downto 0);
    a : IN STD_LOGIC_VECTOR (7 downto 0);
    w : IN STD_LOGIC_VECTOR (7 downto 0);
    done : OUT STD_LOGIC;
    res : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of MAC_small_hls is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "MAC_small_hls_MAC_small_hls,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=10.110000,HLS_SYN_LAT=4,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=460,HLS_SYN_LUT=311,HLS_VERSION=2020_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv12_27 : STD_LOGIC_VECTOR (11 downto 0) := "000000100111";

    signal ap_rst : STD_LOGIC;
    signal d : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal r : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal i : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal have_all : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal weights_V_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal weights_V_ce0 : STD_LOGIC;
    signal weights_V_we0 : STD_LOGIC;
    signal weights_V_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal activations_V_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal activations_V_ce0 : STD_LOGIC;
    signal activations_V_we0 : STD_LOGIC;
    signal activations_V_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal valid_read_read_fu_86_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal valid_read_reg_266 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal valid_read_reg_266_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal valid_read_reg_266_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal valid_read_reg_266_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal rst_read_read_fu_92_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rst_read_reg_270 : STD_LOGIC_VECTOR (0 downto 0);
    signal rst_read_reg_270_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal rst_read_reg_270_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal rst_read_reg_270_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal d_load_load_fu_180_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal d_load_reg_274 : STD_LOGIC_VECTOR (0 downto 0);
    signal d_load_reg_274_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal d_load_reg_274_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal d_load_reg_274_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal have_all_load_load_fu_188_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal have_all_load_reg_279 : STD_LOGIC_VECTOR (0 downto 0);
    signal have_all_load_reg_279_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal have_all_load_reg_279_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal have_all_load_reg_279_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_fu_192_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_reg_283 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_reg_283_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_reg_283_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_reg_283_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal r_load_reg_310 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal zext_ln50_fu_204_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln538_fu_222_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln874_fu_228_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_allocacmp_r_load : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_257_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln51_fu_210_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_257 : BOOLEAN;
    signal ap_condition_254 : BOOLEAN;

    component MAC_small_hls_mac_muladd_8s_8s_32ns_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component MAC_small_hls_weights_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    ap_rst <= not rst_r;
    weights_V_U : component MAC_small_hls_weights_V
    generic map (
        DataWidth => 8,
        AddressRange => 41,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => weights_V_address0,
        ce0 => weights_V_ce0,
        we0 => weights_V_we0,
        d0 => w,
        q0 => weights_V_q0);

    activations_V_U : component MAC_small_hls_weights_V
    generic map (
        DataWidth => 8,
        AddressRange => 41,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => activations_V_address0,
        ce0 => activations_V_ce0,
        we0 => activations_V_we0,
        d0 => a,
        q0 => activations_V_q0);

    mac_muladd_8s_8s_32ns_32_4_1_U1 : component MAC_small_hls_mac_muladd_8s_8s_32ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => activations_V_q0,
        din1 => weights_V_q0,
        din2 => ap_sig_allocacmp_r_load,
        ce => ap_const_logic_1,
        dout => grp_fu_257_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    d_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln49_fu_192_p2 = ap_const_lv1_0) and (have_all_load_load_fu_188_p1 = ap_const_lv1_1) and (d_load_load_fu_180_p1 = ap_const_lv1_0) and (rst_read_read_fu_92_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (valid_read_read_fu_86_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1))) then 
                d <= ap_const_lv1_1;
            elsif ((((rst_read_read_fu_92_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (valid_read_read_fu_86_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln874_fu_228_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_const_logic_1)) or ((rst_read_read_fu_92_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1)))) then 
                d <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    have_all_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((rst_read_read_fu_92_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (valid_read_read_fu_86_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln874_fu_228_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_const_logic_1))) then 
                have_all <= ap_const_lv1_1;
            elsif ((((d_load_load_fu_180_p1 = ap_const_lv1_1) and (rst_read_read_fu_92_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (valid_read_read_fu_86_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1)) or ((rst_read_read_fu_92_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1)))) then 
                have_all <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    i_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln49_fu_192_p2 = ap_const_lv1_1) and (have_all_load_load_fu_188_p1 = ap_const_lv1_1) and (d_load_load_fu_180_p1 = ap_const_lv1_0) and (rst_read_read_fu_92_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (valid_read_read_fu_86_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1))) then 
                i <= add_ln51_fu_210_p2;
            elsif ((((icmp_ln49_fu_192_p2 = ap_const_lv1_0) and (have_all_load_load_fu_188_p1 = ap_const_lv1_1) and (d_load_load_fu_180_p1 = ap_const_lv1_0) and (rst_read_read_fu_92_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (valid_read_read_fu_86_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1)) or ((rst_read_read_fu_92_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1)))) then 
                i <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    r_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln49_reg_283_pp0_iter3_reg = ap_const_lv1_1) and (have_all_load_reg_279_pp0_iter3_reg = ap_const_lv1_1) and (d_load_reg_274_pp0_iter3_reg = ap_const_lv1_0) and (rst_read_reg_270_pp0_iter3_reg = ap_const_lv1_1) and (valid_read_reg_266_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
                r <= grp_fu_257_p3;
            elsif ((((rst_read_reg_270_pp0_iter3_reg = ap_const_lv1_1) and (valid_read_reg_266_pp0_iter3_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((rst_read_reg_270_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)))) then 
                r <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                d_load_reg_274 <= d;
                d_load_reg_274_pp0_iter1_reg <= d_load_reg_274;
                have_all_load_reg_279 <= have_all;
                have_all_load_reg_279_pp0_iter1_reg <= have_all_load_reg_279;
                icmp_ln49_reg_283_pp0_iter1_reg <= icmp_ln49_reg_283;
                rst_read_reg_270 <= (0=>rst_r, others=>'-');
                rst_read_reg_270_pp0_iter1_reg <= rst_read_reg_270;
                valid_read_reg_266 <= (0=>valid, others=>'-');
                valid_read_reg_266_pp0_iter1_reg <= valid_read_reg_266;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                d_load_reg_274_pp0_iter2_reg <= d_load_reg_274_pp0_iter1_reg;
                d_load_reg_274_pp0_iter3_reg <= d_load_reg_274_pp0_iter2_reg;
                have_all_load_reg_279_pp0_iter2_reg <= have_all_load_reg_279_pp0_iter1_reg;
                have_all_load_reg_279_pp0_iter3_reg <= have_all_load_reg_279_pp0_iter2_reg;
                icmp_ln49_reg_283_pp0_iter2_reg <= icmp_ln49_reg_283_pp0_iter1_reg;
                icmp_ln49_reg_283_pp0_iter3_reg <= icmp_ln49_reg_283_pp0_iter2_reg;
                r_load_reg_310 <= ap_sig_allocacmp_r_load;
                rst_read_reg_270_pp0_iter2_reg <= rst_read_reg_270_pp0_iter1_reg;
                rst_read_reg_270_pp0_iter3_reg <= rst_read_reg_270_pp0_iter2_reg;
                valid_read_reg_266_pp0_iter2_reg <= valid_read_reg_266_pp0_iter1_reg;
                valid_read_reg_266_pp0_iter3_reg <= valid_read_reg_266_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((have_all_load_load_fu_188_p1 = ap_const_lv1_1) and (d_load_load_fu_180_p1 = ap_const_lv1_0) and (rst_read_read_fu_92_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (valid_read_read_fu_86_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln49_reg_283 <= icmp_ln49_fu_192_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    activations_V_address0_assign_proc : process(valid_read_read_fu_86_p2, zext_ln50_fu_204_p1, zext_ln538_fu_222_p1, ap_condition_257, ap_condition_254)
    begin
        if ((ap_const_boolean_1 = ap_condition_254)) then
            if ((valid_read_read_fu_86_p2 = ap_const_lv1_1)) then 
                activations_V_address0 <= zext_ln538_fu_222_p1(6 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_257)) then 
                activations_V_address0 <= zext_ln50_fu_204_p1(6 - 1 downto 0);
            else 
                activations_V_address0 <= "XXXXXX";
            end if;
        else 
            activations_V_address0 <= "XXXXXX";
        end if; 
    end process;


    activations_V_ce0_assign_proc : process(valid_read_read_fu_86_p2, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, rst_read_read_fu_92_p2, d_load_load_fu_180_p1, have_all_load_load_fu_188_p1, icmp_ln49_fu_192_p2)
    begin
        if ((((icmp_ln49_fu_192_p2 = ap_const_lv1_1) and (have_all_load_load_fu_188_p1 = ap_const_lv1_1) and (d_load_load_fu_180_p1 = ap_const_lv1_0) and (rst_read_read_fu_92_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (valid_read_read_fu_86_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1)) or ((rst_read_read_fu_92_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (valid_read_read_fu_86_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1)))) then 
            activations_V_ce0 <= ap_const_logic_1;
        else 
            activations_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    activations_V_we0_assign_proc : process(valid_read_read_fu_86_p2, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, rst_read_read_fu_92_p2)
    begin
        if (((rst_read_read_fu_92_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (valid_read_read_fu_86_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1))) then 
            activations_V_we0 <= ap_const_logic_1;
        else 
            activations_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln51_fu_210_p2 <= std_logic_vector(unsigned(i) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_254_assign_proc : process(ap_CS_fsm_pp0_stage0, rst_read_read_fu_92_p2, ap_block_pp0_stage0)
    begin
                ap_condition_254 <= ((rst_read_read_fu_92_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1));
    end process;


    ap_condition_257_assign_proc : process(valid_read_read_fu_86_p2, d_load_load_fu_180_p1, have_all_load_load_fu_188_p1, icmp_ln49_fu_192_p2)
    begin
                ap_condition_257 <= ((icmp_ln49_fu_192_p2 = ap_const_lv1_1) and (have_all_load_load_fu_188_p1 = ap_const_lv1_1) and (d_load_load_fu_180_p1 = ap_const_lv1_0) and (valid_read_read_fu_86_p2 = ap_const_lv1_0));
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_reset_idle_pp0 <= ap_const_logic_0;

    ap_sig_allocacmp_r_load_assign_proc : process(r, valid_read_reg_266_pp0_iter3_reg, rst_read_reg_270_pp0_iter3_reg, d_load_reg_274_pp0_iter3_reg, have_all_load_reg_279_pp0_iter3_reg, icmp_ln49_reg_283_pp0_iter3_reg, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0, grp_fu_257_p3)
    begin
        if (((icmp_ln49_reg_283_pp0_iter3_reg = ap_const_lv1_1) and (have_all_load_reg_279_pp0_iter3_reg = ap_const_lv1_1) and (d_load_reg_274_pp0_iter3_reg = ap_const_lv1_0) and (rst_read_reg_270_pp0_iter3_reg = ap_const_lv1_1) and (valid_read_reg_266_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            ap_sig_allocacmp_r_load <= grp_fu_257_p3;
        elsif ((((rst_read_reg_270_pp0_iter3_reg = ap_const_lv1_1) and (valid_read_reg_266_pp0_iter3_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((rst_read_reg_270_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)))) then 
            ap_sig_allocacmp_r_load <= ap_const_lv32_0;
        else 
            ap_sig_allocacmp_r_load <= r;
        end if; 
    end process;

    d_load_load_fu_180_p1 <= d;
    done <= d_load_reg_274_pp0_iter3_reg(0);
    have_all_load_load_fu_188_p1 <= have_all;
    icmp_ln49_fu_192_p2 <= "1" when (signed(i) < signed(ap_const_lv32_28)) else "0";
    icmp_ln874_fu_228_p2 <= "1" when (idx = ap_const_lv12_27) else "0";
    res <= r_load_reg_310;
    rst_read_read_fu_92_p2 <= (0=>rst_r, others=>'-');
    valid_read_read_fu_86_p2 <= (0=>valid, others=>'-');

    weights_V_address0_assign_proc : process(valid_read_read_fu_86_p2, zext_ln50_fu_204_p1, zext_ln538_fu_222_p1, ap_condition_257, ap_condition_254)
    begin
        if ((ap_const_boolean_1 = ap_condition_254)) then
            if ((valid_read_read_fu_86_p2 = ap_const_lv1_1)) then 
                weights_V_address0 <= zext_ln538_fu_222_p1(6 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_257)) then 
                weights_V_address0 <= zext_ln50_fu_204_p1(6 - 1 downto 0);
            else 
                weights_V_address0 <= "XXXXXX";
            end if;
        else 
            weights_V_address0 <= "XXXXXX";
        end if; 
    end process;


    weights_V_ce0_assign_proc : process(valid_read_read_fu_86_p2, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, rst_read_read_fu_92_p2, d_load_load_fu_180_p1, have_all_load_load_fu_188_p1, icmp_ln49_fu_192_p2)
    begin
        if ((((icmp_ln49_fu_192_p2 = ap_const_lv1_1) and (have_all_load_load_fu_188_p1 = ap_const_lv1_1) and (d_load_load_fu_180_p1 = ap_const_lv1_0) and (rst_read_read_fu_92_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (valid_read_read_fu_86_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1)) or ((rst_read_read_fu_92_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (valid_read_read_fu_86_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1)))) then 
            weights_V_ce0 <= ap_const_logic_1;
        else 
            weights_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    weights_V_we0_assign_proc : process(valid_read_read_fu_86_p2, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, rst_read_read_fu_92_p2)
    begin
        if (((rst_read_read_fu_92_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (valid_read_read_fu_86_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1))) then 
            weights_V_we0 <= ap_const_logic_1;
        else 
            weights_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln50_fu_204_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i),64));
    zext_ln538_fu_222_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(idx),64));
end behav;
