-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity MAC_hls is
port (
    ap_clk : IN STD_LOGIC;
    rst_r : IN STD_LOGIC;
    valid : IN STD_LOGIC;
    idx : IN STD_LOGIC_VECTOR (11 downto 0);
    a : IN STD_LOGIC_VECTOR (7 downto 0);
    w : IN STD_LOGIC_VECTOR (7 downto 0);
    done : OUT STD_LOGIC;
    res : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of MAC_hls is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "MAC_hls_MAC_hls,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=10.110000,HLS_SYN_LAT=3,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=475,HLS_SYN_LUT=307,HLS_VERSION=2020_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv12_2 : STD_LOGIC_VECTOR (11 downto 0) := "000000000010";

    signal ap_rst : STD_LOGIC;
    signal d : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal r : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal i : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal have_all : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal weights_V_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weights_V_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weights_V_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal activations_V_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal activations_V_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal activations_V_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal valid_read_read_fu_100_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal valid_read_reg_320 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal valid_read_reg_320_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal valid_read_reg_320_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal rst_read_read_fu_106_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rst_read_reg_324 : STD_LOGIC_VECTOR (0 downto 0);
    signal rst_read_reg_324_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal rst_read_reg_324_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal d_load_load_fu_150_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal d_load_reg_328 : STD_LOGIC_VECTOR (0 downto 0);
    signal d_load_reg_328_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal d_load_reg_328_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal have_all_load_load_fu_158_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal have_all_load_reg_333 : STD_LOGIC_VECTOR (0 downto 0);
    signal have_all_load_reg_333_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal have_all_load_reg_333_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_fu_186_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_reg_337 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_reg_337_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_reg_337_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal r_load_reg_357 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal icmp_ln874_fu_290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_sig_allocacmp_r_load : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_311_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln51_fu_238_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln182_fu_250_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal trunc_ln69_fu_198_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal phi_ln_fu_202_p6 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln69_1_fu_216_p6 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;

    component MAC_hls_mux_42_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component MAC_hls_mac_muladd_8s_8s_32ns_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    ap_rst <= not rst_r;
    mux_42_8_1_1_U1 : component MAC_hls_mux_42_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => weights_V_0,
        din1 => weights_V_1,
        din2 => weights_V_2,
        din3 => weights_V_2,
        din4 => trunc_ln69_fu_198_p1,
        dout => phi_ln_fu_202_p6);

    mux_42_8_1_1_U2 : component MAC_hls_mux_42_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => activations_V_0,
        din1 => activations_V_1,
        din2 => activations_V_2,
        din3 => activations_V_2,
        din4 => trunc_ln69_fu_198_p1,
        dout => phi_ln69_1_fu_216_p6);

    mac_muladd_8s_8s_32ns_32_4_1_U3 : component MAC_hls_mac_muladd_8s_8s_32ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => phi_ln_fu_202_p6,
        din1 => phi_ln69_1_fu_216_p6,
        din2 => ap_sig_allocacmp_r_load,
        ce => ap_const_logic_1,
        dout => grp_fu_311_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    d_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_const_logic_1) and (icmp_ln49_fu_186_p2 = ap_const_lv1_0) and (have_all_load_load_fu_158_p1 = ap_const_lv1_1) and (d_load_load_fu_150_p1 = ap_const_lv1_0) and (rst_read_read_fu_106_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (valid_read_read_fu_100_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                d <= ap_const_lv1_1;
            elsif ((((ap_const_logic_1 = ap_const_logic_1) and (rst_read_read_fu_106_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_logic_1 = ap_const_logic_1) and (rst_read_read_fu_106_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (valid_read_read_fu_100_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln874_fu_290_p2 = ap_const_lv1_1)))) then 
                d <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    have_all_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_const_logic_1) and (rst_read_read_fu_106_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (valid_read_read_fu_100_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln874_fu_290_p2 = ap_const_lv1_1))) then 
                have_all <= ap_const_lv1_1;
            elsif ((((ap_const_logic_1 = ap_const_logic_1) and (rst_read_read_fu_106_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_logic_1 = ap_const_logic_1) and (d_load_load_fu_150_p1 = ap_const_lv1_1) and (rst_read_read_fu_106_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (valid_read_read_fu_100_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                have_all <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    i_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_const_logic_1) and (icmp_ln49_fu_186_p2 = ap_const_lv1_1) and (have_all_load_load_fu_158_p1 = ap_const_lv1_1) and (d_load_load_fu_150_p1 = ap_const_lv1_0) and (rst_read_read_fu_106_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (valid_read_read_fu_100_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                i <= add_ln51_fu_238_p2;
            elsif ((((ap_const_logic_1 = ap_const_logic_1) and (icmp_ln49_fu_186_p2 = ap_const_lv1_0) and (have_all_load_load_fu_158_p1 = ap_const_lv1_1) and (d_load_load_fu_150_p1 = ap_const_lv1_0) and (rst_read_read_fu_106_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (valid_read_read_fu_100_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_logic_1 = ap_const_logic_1) and (rst_read_read_fu_106_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                i <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    r_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln49_reg_337_pp0_iter2_reg = ap_const_lv1_1) and (have_all_load_reg_333_pp0_iter2_reg = ap_const_lv1_1) and (d_load_reg_328_pp0_iter2_reg = ap_const_lv1_0) and (rst_read_reg_324_pp0_iter2_reg = ap_const_lv1_1) and (valid_read_reg_320_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                r <= grp_fu_311_p3;
            elsif ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (rst_read_reg_324_pp0_iter2_reg = ap_const_lv1_1) and (valid_read_reg_320_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (rst_read_reg_324_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                r <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_const_logic_1) and (rst_read_read_fu_106_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (valid_read_read_fu_100_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln182_fu_250_p1 = ap_const_lv2_0))) then
                activations_V_0 <= a;
                weights_V_0 <= w;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_const_logic_1) and (rst_read_read_fu_106_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (valid_read_read_fu_100_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln182_fu_250_p1 = ap_const_lv2_1))) then
                activations_V_1 <= a;
                weights_V_1 <= w;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_const_logic_1) and (rst_read_read_fu_106_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (valid_read_read_fu_100_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln182_fu_250_p1 = ap_const_lv2_2))) then
                activations_V_2 <= a;
                weights_V_2 <= w;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                d_load_reg_328 <= d;
                d_load_reg_328_pp0_iter1_reg <= d_load_reg_328;
                have_all_load_reg_333 <= have_all;
                have_all_load_reg_333_pp0_iter1_reg <= have_all_load_reg_333;
                icmp_ln49_reg_337_pp0_iter1_reg <= icmp_ln49_reg_337;
                rst_read_reg_324 <= (0=>rst_r, others=>'-');
                rst_read_reg_324_pp0_iter1_reg <= rst_read_reg_324;
                valid_read_reg_320 <= (0=>valid, others=>'-');
                valid_read_reg_320_pp0_iter1_reg <= valid_read_reg_320;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                d_load_reg_328_pp0_iter2_reg <= d_load_reg_328_pp0_iter1_reg;
                have_all_load_reg_333_pp0_iter2_reg <= have_all_load_reg_333_pp0_iter1_reg;
                icmp_ln49_reg_337_pp0_iter2_reg <= icmp_ln49_reg_337_pp0_iter1_reg;
                r_load_reg_357 <= ap_sig_allocacmp_r_load;
                rst_read_reg_324_pp0_iter2_reg <= rst_read_reg_324_pp0_iter1_reg;
                valid_read_reg_320_pp0_iter2_reg <= valid_read_reg_320_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((have_all_load_load_fu_158_p1 = ap_const_lv1_1) and (d_load_load_fu_150_p1 = ap_const_lv1_0) and (rst_read_read_fu_106_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (valid_read_read_fu_100_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln49_reg_337 <= icmp_ln49_fu_186_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln51_fu_238_p2 <= std_logic_vector(unsigned(ap_const_lv32_1) + unsigned(i));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_reset_idle_pp0 <= ap_const_logic_0;

    ap_sig_allocacmp_r_load_assign_proc : process(r, valid_read_reg_320_pp0_iter2_reg, rst_read_reg_324_pp0_iter2_reg, d_load_reg_328_pp0_iter2_reg, have_all_load_reg_333_pp0_iter2_reg, icmp_ln49_reg_337_pp0_iter2_reg, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, grp_fu_311_p3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln49_reg_337_pp0_iter2_reg = ap_const_lv1_1) and (have_all_load_reg_333_pp0_iter2_reg = ap_const_lv1_1) and (d_load_reg_328_pp0_iter2_reg = ap_const_lv1_0) and (rst_read_reg_324_pp0_iter2_reg = ap_const_lv1_1) and (valid_read_reg_320_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_r_load <= grp_fu_311_p3;
        elsif ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (rst_read_reg_324_pp0_iter2_reg = ap_const_lv1_1) and (valid_read_reg_320_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (rst_read_reg_324_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            ap_sig_allocacmp_r_load <= ap_const_lv32_0;
        else 
            ap_sig_allocacmp_r_load <= r;
        end if; 
    end process;

    d_load_load_fu_150_p1 <= d;
    done <= d_load_reg_328_pp0_iter2_reg(0);
    have_all_load_load_fu_158_p1 <= have_all;
    icmp_ln49_fu_186_p2 <= "1" when (signed(i) < signed(ap_const_lv32_3)) else "0";
    icmp_ln874_fu_290_p2 <= "1" when (idx = ap_const_lv12_2) else "0";
    res <= r_load_reg_357;
    rst_read_read_fu_106_p2 <= (0=>rst_r, others=>'-');
    trunc_ln182_fu_250_p1 <= idx(2 - 1 downto 0);
    trunc_ln69_fu_198_p1 <= i(2 - 1 downto 0);
    valid_read_read_fu_100_p2 <= (0=>valid, others=>'-');
end behav;
