# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/soc_task_1/soc_task_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_task_1 || ORIG_REF_NAME==soc_task_1} -quiet] -quiet

# IP: bd/soc_task_1/ip/soc_task_1_axi_gpio_0_1/soc_task_1_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_task_1_axi_gpio_0_1 || ORIG_REF_NAME==soc_task_1_axi_gpio_0_1} -quiet] -quiet

# IP: bd/soc_task_1/ip/soc_task_1_axi_gpio_1_1/soc_task_1_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_task_1_axi_gpio_1_1 || ORIG_REF_NAME==soc_task_1_axi_gpio_1_1} -quiet] -quiet

# IP: bd/soc_task_1/ip/soc_task_1_axi_gpio_10_1/soc_task_1_axi_gpio_10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_task_1_axi_gpio_10_1 || ORIG_REF_NAME==soc_task_1_axi_gpio_10_1} -quiet] -quiet

# IP: bd/soc_task_1/ip/soc_task_1_axi_gpio_11_1/soc_task_1_axi_gpio_11_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_task_1_axi_gpio_11_1 || ORIG_REF_NAME==soc_task_1_axi_gpio_11_1} -quiet] -quiet

# IP: bd/soc_task_1/ip/soc_task_1_axi_gpio_2_1/soc_task_1_axi_gpio_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_task_1_axi_gpio_2_1 || ORIG_REF_NAME==soc_task_1_axi_gpio_2_1} -quiet] -quiet

# IP: bd/soc_task_1/ip/soc_task_1_axi_gpio_3_1/soc_task_1_axi_gpio_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_task_1_axi_gpio_3_1 || ORIG_REF_NAME==soc_task_1_axi_gpio_3_1} -quiet] -quiet

# IP: bd/soc_task_1/ip/soc_task_1_axi_gpio_4_1/soc_task_1_axi_gpio_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_task_1_axi_gpio_4_1 || ORIG_REF_NAME==soc_task_1_axi_gpio_4_1} -quiet] -quiet

# IP: bd/soc_task_1/ip/soc_task_1_axi_gpio_5_1/soc_task_1_axi_gpio_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_task_1_axi_gpio_5_1 || ORIG_REF_NAME==soc_task_1_axi_gpio_5_1} -quiet] -quiet

# IP: bd/soc_task_1/ip/soc_task_1_axi_gpio_6_1/soc_task_1_axi_gpio_6_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_task_1_axi_gpio_6_1 || ORIG_REF_NAME==soc_task_1_axi_gpio_6_1} -quiet] -quiet

# IP: bd/soc_task_1/ip/soc_task_1_axi_gpio_7_1/soc_task_1_axi_gpio_7_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_task_1_axi_gpio_7_1 || ORIG_REF_NAME==soc_task_1_axi_gpio_7_1} -quiet] -quiet

# IP: bd/soc_task_1/ip/soc_task_1_axi_gpio_8_1/soc_task_1_axi_gpio_8_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_task_1_axi_gpio_8_1 || ORIG_REF_NAME==soc_task_1_axi_gpio_8_1} -quiet] -quiet

# IP: bd/soc_task_1/ip/soc_task_1_axi_gpio_9_1/soc_task_1_axi_gpio_9_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_task_1_axi_gpio_9_1 || ORIG_REF_NAME==soc_task_1_axi_gpio_9_1} -quiet] -quiet

# IP: bd/soc_task_1/ip/soc_task_1_xbar_1/soc_task_1_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_task_1_xbar_1 || ORIG_REF_NAME==soc_task_1_xbar_1} -quiet] -quiet

# IP: bd/soc_task_1/ip/soc_task_1_axi_interconnect_0_1/soc_task_1_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_task_1_axi_interconnect_0_1 || ORIG_REF_NAME==soc_task_1_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/soc_task_1/ip/soc_task_1_proc_sys_reset_0_1/soc_task_1_proc_sys_reset_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_task_1_proc_sys_reset_0_1 || ORIG_REF_NAME==soc_task_1_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/soc_task_1/ip/soc_task_1_processing_system7_0_1/soc_task_1_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_task_1_processing_system7_0_1 || ORIG_REF_NAME==soc_task_1_processing_system7_0_1} -quiet] -quiet

# IP: bd/soc_task_1/ip/soc_task_1_MAC_big_hls_0_1/soc_task_1_MAC_big_hls_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_task_1_MAC_big_hls_0_1 || ORIG_REF_NAME==soc_task_1_MAC_big_hls_0_1} -quiet] -quiet

# IP: bd/soc_task_1/ip/soc_task_1_MAC_small_hls_0_2/soc_task_1_MAC_small_hls_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_task_1_MAC_small_hls_0_2 || ORIG_REF_NAME==soc_task_1_MAC_small_hls_0_2} -quiet] -quiet

# IP: bd/soc_task_1/ip/soc_task_1_auto_pc_0/soc_task_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_task_1_auto_pc_0 || ORIG_REF_NAME==soc_task_1_auto_pc_0} -quiet] -quiet

# XDC: bd/soc_task_1/soc_task_1_ooc.xdc
